pma:
  image: phpmyadmin/phpmyadmin
  container_name: pma-htpasswd
  environment:
    PMA_HOST: ip_or_host

nginx_htpasswd:
  build: nginx
  container_name: nginx-htpasswd
  environment:
    NGINX_PROXY_HTPASSWD_DOMAIN: pma
    NGINX_PROXY_HTPASSWD_USERNAME: admin
    NGINX_PROXY_HTPASSWD_PASSWORD: htpasswd_changeme
  links:
    - pma:pma
  ports:
    - 3010:8080
